// Column order matches the Google Sheet. Used for CSV export and the detail view.
export const SHEET_COLUMNS = [
  { key: 'timestamp', label: 'Timestamp' },
  { key: 'applicationId', label: 'Application ID' },
  { key: 'fullName', label: 'Full Name' },
  { key: 'registrationNumber', label: 'Registration Number' },
  { key: 'course', label: 'Course' },
  { key: 'year', label: 'Year' },
  { key: 'phone', label: 'Phone' },
  { key: 'email', label: 'Email' },
  { key: 'membership', label: 'Club Membership' },
  { key: 'membershipDuration', label: 'Membership Duration' },
  { key: 'position', label: 'Position Applied For' },
  { key: 'leadershipMotivation', label: 'Leadership Motivation' },
  { key: 'positionMotivation', label: 'Position Motivation' },
  { key: 'leadershipDefinition', label: 'Leadership Definition' },
  { key: 'leadershipExperience', label: 'Leadership Experience' },
  { key: 'leadershipQualities', label: 'Leadership Qualities' },
  { key: 'conflictResolution', label: 'Conflict Resolution' },
  { key: 'academicBalance', label: 'Academic/Club Balance' },
  { key: 'clubVision', label: 'Club Vision' },
  { key: 'proposedActivities', label: 'Three Proposed Activities' },
  { key: 'engagementStrategy', label: 'Member Engagement Strategy' },
  { key: 'francophoneImportance', label: 'French/Francophone Importance' },
  { key: 'positionAnswer1', label: 'Position-Specific Answer 1' },
  { key: 'positionAnswer2', label: 'Position-Specific Answer 2' },
  { key: 'positionAnswer3', label: 'Position-Specific Answer 3' },
  { key: 'frenchProficiency', label: 'French Proficiency' },
  { key: 'frenchIntroduction', label: 'French Introduction' },
  { key: 'cultureInterest', label: 'Francophone Culture Interest' },
  { key: 'meetingCommitment', label: 'Meeting Commitment' },
  { key: 'activityCommitment', label: 'Activity Commitment' },
  { key: 'leadershipCommitment', label: 'Leadership Commitment' },
  { key: 'declaration', label: 'Declaration' },
  { key: 'status', label: 'Application Status' },
  { key: 'adminNotes', label: 'Admin Notes' },
  { key: 'lastEmailedStatus', label: 'Last Emailed Status' },
  { key: 'lastEmailedAt', label: 'Last Emailed At' },
];

export const DETAIL_GROUPS = [
  { title: 'Personal information', keys: ['fullName', 'registrationNumber', 'course', 'year', 'phone', 'email'] },
  { title: 'Club information', keys: ['membership', 'membershipDuration', 'position'] },
  { title: 'Leadership', keys: ['leadershipMotivation', 'positionMotivation', 'leadershipDefinition', 'leadershipExperience', 'leadershipQualities', 'conflictResolution', 'academicBalance'] },
  { title: 'Vision for the club', keys: ['clubVision', 'proposedActivities', 'engagementStrategy', 'francophoneImportance'] },
  { title: 'Position-specific answers', keys: ['positionAnswer1', 'positionAnswer2', 'positionAnswer3'], positional: true },
  { title: 'French language and culture', keys: ['frenchProficiency', 'frenchIntroduction', 'cultureInterest'] },
  { title: 'Commitment and declaration', keys: ['meetingCommitment', 'activityCommitment', 'leadershipCommitment', 'declaration'] },
];

export const labelFor = (key) => SHEET_COLUMNS.find((c) => c.key === key)?.label || key;
